# Numpy

In [119]:
import numpy as np



Lists and tuples have a defined order, so NumPy naturally converts each element into an array element. Sets don't have a guaranteed order, so NumPy deliberately treats the entire set as a single Python object (dtype=object) instead of automatically creating a numeric array from its elements.

In [120]:
# Create array using numpy
arr1 = np.array({1,2,3,4,5})
arr1

array({1, 2, 3, 4, 5}, dtype=object)

In [121]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [122]:
print(type(arr1))

<class 'numpy.ndarray'>

In [123]:
print(arr1.shape)

()

In [124]:
arr3 = np.array([{1,2,3}])
arr3.shape

(1,)

In [125]:
np.arange(0,10) # arange() can be used to create a array of elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.ones((2,3)) # It creates a array of given shape and dtype , all filled with ones(if no dtype is given,by default it gives a array with floats)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [127]:
np.eye(3) # Used to create an identity matrix (it gives a 2D array)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("Shape :" , arr.shape) # Shape of the array
print("No of dimensions:",arr.ndim) # How many dimensions is that array of ?
print("Size:",arr.size) # No of elements in the array
print("Data type:",arr.dtype) #what is the datatype fo that array elements
print("Item size:",arr.itemsize) # How many bytes are being utilised to create the array?

[[1 2 3]
 [4 5 6]]
Shape : (2, 3)
No of dimensions: 2
Size: 6
Data type: int64
Item size: 8

In [129]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,3,4,5,4])
print("Addition:" , arr1+arr2)
print("Substraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)
print("Divison:",arr1/arr2)

Addition: [2 5 7 9 9]
Substraction: [ 0 -1 -1 -1  1]
Multiplication: [ 1  6 12 20 20]
Divison: [1.         0.66666667 0.75       0.8        1.25      ]

In [130]:
arr = np.array([2,3,4,5])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log1p(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[1.09861229 1.38629436 1.60943791 1.79175947]
[0.69314718 1.09861229 1.38629436 1.60943791]

In [131]:
#Array Slicing and Indexing

arr = np.arange(3,15).reshape(3,4)
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [132]:
arr[0][1] # Indexing

4

In [133]:
arr[0:,2:] # Slicing

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [134]:
arr[0:]

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [135]:

'''
Here is it is 2 separate slicing operations , it is like 
temp = arr[1:]
temp[2:]
It has 4 cols because, though there are no rows(no elements) , but if there were , it would have had 4 cols 
Currently it is empty
'''
arr[1:][2:]

array([], shape=(0, 4), dtype=int64)

In [136]:
arr[1:,2:]

array([[ 9, 10],
       [13, 14]])

In [137]:
arr[:][:]

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [138]:
arr[0:][0:]

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [139]:
data = np.array([1,2,3,4,5,6])
mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)
median = np.median(data)


normalised_data = (data-mean)/std_dev
print(normalised_data)
print(median)
print(variance)
print(std_dev)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
3.5
2.9166666666666665
1.707825127659933

In [140]:
data = np.array([1,2,43,4,4,5,5,6])
new = data[data>5] # Logical operation
new

array([43,  6])

# Pandas

In [141]:
import pandas as pd

Series is a 1D array like object that can hold any data type. It is similar to a column in a table

In [142]:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [143]:
data1 = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data1)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [144]:
data = [10,20,30]
indexes = ['a','b','c']
pd.Series(data,index = indexes)

a    10
b    20
c    30
dtype: int64

In [145]:
# Data Frame from dictionary of lists
data = {
    'name':['Pranav','Aditya','Gunda'],
    'age':[25,30,40],
    'city':['Bangalore','Hyderabad','New York']
}

df = pd.DataFrame(data)
df

     name  age       city
0  Pranav   25  Bangalore
1  Aditya   30  Hyderabad
2   Gunda   40   New York

In [146]:
# Data Frame from list of dictionaries
data1 = [{'Name':'Pranav','Age':22,'City':'Hyderabad'},
         {'Name':'Aditya','Age':25,'City':'Bangalore'},
         {'Name':'Gunda','Age':30,'City':'Chennai'}
         ]

df1 = pd.DataFrame(data1)
df1

     Name  Age       City
0  Pranav   22  Hyderabad
1  Aditya   25  Bangalore
2   Gunda   30    Chennai

In [147]:
df2 = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/Online Sales Data.csv')
df2.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [148]:
df2.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [149]:
type(df2['Region'])

pandas.Series

In [150]:
df2.loc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [151]:
df2.iloc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [152]:
df2.at[2,'Product Category']

'Clothing'

In [153]:
df2.iat[2,2]

'Clothing'

In [154]:
df2['Kuchbhi'] = [x for x in range(1,241)]
df2

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Kuchbhi
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,2
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,3
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,4
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,5
...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,236
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,237
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,238
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,239
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,240

In [155]:
df2.drop('Kuchbhi',axis=1,inplace = True)

In [156]:
df2

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [157]:
df2['Total Revenue']=df2['Total Revenue']+1
df2

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,2000.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,500.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,210.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,64.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,90.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,160.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,271.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,33.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,56.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,60.98,Asia,Credit Card

In [158]:
print(df2.dtypes)
print(df.describe())

Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
             age
count   3.000000
mean   31.666667
std     7.637626
min    25.000000
25%    27.500000
50%    30.000000
75%    35.000000
max    40.000000

In [159]:
grouped = df2.groupby('Product Category')['Total Revenue'].mean()
grouped

Product Category
Beauty Products     66.54750
Books               47.54825
Clothing           204.22325
Electronics        875.56025
Home Appliances    467.15400
Sports             359.16300
Name: Total Revenue, dtype: float64

### loc is used for label based indexing 
### iloc is used for integer position based indexing

In [160]:
import pandas as pd

df4 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [22, 25, 30, 28],
    "City": ["Delhi", "Mumbai", "Bangalore", "Hyderabad"]
})

print(df4)

      Name  Age       City
0    Alice   22      Delhi
1      Bob   25     Mumbai
2  Charlie   30  Bangalore
3    David   28  Hyderabad

In [161]:
df.iloc[1,2]

'Hyderabad'

In [162]:
df.iloc[0:2]

     name  age       city
0  Pranav   25  Bangalore
1  Aditya   30  Hyderabad

In [163]:
df.loc[0:2]

     name  age       city
0  Pranav   25  Bangalore
1  Aditya   30  Hyderabad
2   Gunda   40   New York

In [164]:
# Handline Missing Values
# First find how many missing values are there in each column 
print(df2.isnull().sum())
# Find rows containing the missing values
df2[df2.isnull().any(axis=1)]

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

Empty DataFrame
Columns: [Transaction ID, Date, Product Category, Product Name, Units Sold, Unit Price, Total Revenue, Region, Payment Method]
Index: []

In [165]:
# Filling missing values with the mean of the column
df2['Unit Price_clean'] = df2['Unit Price'].fillna(df2['Unit Price'].mean())
df2

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Unit Price_clean
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,2000.98,North America,Credit Card,999.99
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,500.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,210.97,Asia,Debit Card,69.99
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,64.96,North America,Credit Card,15.99
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,90.99,Europe,PayPal,89.99
...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,160.99,Europe,PayPal,159.99
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,271.00,Asia,Debit Card,90.00
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,33.97,North America,Credit Card,10.99
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,56.00,Europe,PayPal,55.00
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,60.98,Asia,Credit Card,29.99

In [166]:
## Renaming column
df2 = df2.rename(columns={'Date':'date','Region':'Place'})
df2

,Transaction ID,date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Place,Payment Method,Unit Price_clean
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,2000.98,North America,Credit Card,999.99
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,500.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,210.97,Asia,Debit Card,69.99
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,64.96,North America,Credit Card,15.99
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,90.99,Europe,PayPal,89.99
...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,160.99,Europe,PayPal,159.99
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,271.00,Asia,Debit Card,90.00
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,33.97,North America,Credit Card,10.99
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,56.00,Europe,PayPal,55.00
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,60.98,Asia,Credit Card,29.99

In [167]:
# Change DataTypes
df2.dtypes

Transaction ID        int64
date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Place                   str
Payment Method          str
Unit Price_clean    float64
dtype: object

In [168]:
df2['Units_Sold_Float'] = df2['Units Sold'].astype(float)
df2

,Transaction ID,date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Place,Payment Method,Unit Price_clean,Units_Sold_Float
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,2000.98,North America,Credit Card,999.99,2.0
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,500.99,Europe,PayPal,499.99,1.0
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,210.97,Asia,Debit Card,69.99,3.0
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,64.96,North America,Credit Card,15.99,4.0
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,90.99,Europe,PayPal,89.99,1.0
...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,160.99,Europe,PayPal,159.99,1.0
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,271.00,Asia,Debit Card,90.00,3.0
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,33.97,North America,Credit Card,10.99,3.0
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,56.00,Europe,PayPal,55.00,1.0
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,60.98,Asia,Credit Card,29.99,2.0

In [169]:
df2['New Value'] = df2['Units Sold'].apply(lambda x : x**2)
df2

,Transaction ID,date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Place,Payment Method,Unit Price_clean,Units_Sold_Float,New Value
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,2000.98,North America,Credit Card,999.99,2.0,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,500.99,Europe,PayPal,499.99,1.0,1
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,210.97,Asia,Debit Card,69.99,3.0,9
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,64.96,North America,Credit Card,15.99,4.0,16
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,90.99,Europe,PayPal,89.99,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,160.99,Europe,PayPal,159.99,1.0,1
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,271.00,Asia,Debit Card,90.00,3.0,9
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,33.97,North America,Credit Card,10.99,3.0,9
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,56.00,Europe,PayPal,55.00,1.0,1
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,60.98,Asia,Credit Card,29.99,2.0,4

In [170]:
df2= df2.groupby('Product Name')['New Value'].mean()
df2

Product Name
1984 by George Orwell                                 16.0
Adidas 3-Stripes Shorts                               25.0
Adidas Essential Track Pants                           9.0
Adidas FIFA World Cup Football                         9.0
Adidas Originals Superstar Sneakers                   16.0
                                                      ...
Yeti Tundra Haul Portable Wheeled Cooler               1.0
Youth to the People Superfood Antioxidant Cleanser     1.0
Zara Summer Dress                                      9.0
iPhone 14 Pro                                          4.0
iRobot Braava Jet M6                                   1.0
Name: New Value, Length: 232, dtype: float64

In [171]:
df2

Product Name
1984 by George Orwell                                 16.0
Adidas 3-Stripes Shorts                               25.0
Adidas Essential Track Pants                           9.0
Adidas FIFA World Cup Football                         9.0
Adidas Originals Superstar Sneakers                   16.0
                                                      ...
Yeti Tundra Haul Portable Wheeled Cooler               1.0
Youth to the People Superfood Antioxidant Cleanser     1.0
Zara Summer Dress                                      9.0
iPhone 14 Pro                                          4.0
iRobot Braava Jet M6                                   1.0
Name: New Value, Length: 232, dtype: float64

In [172]:
df2.head(5)

Product Name
1984 by George Orwell                  16.0
Adidas 3-Stripes Shorts                25.0
Adidas Essential Track Pants            9.0
Adidas FIFA World Cup Football          9.0
Adidas Originals Superstar Sneakers    16.0
Name: New Value, dtype: float64

KeyError: 'Column not found: New Value'

In [175]:
df2.head()

Product Name
1984 by George Orwell                  16.0
Adidas 3-Stripes Shorts                25.0
Adidas Essential Track Pants            9.0
Adidas FIFA World Cup Football          9.0
Adidas Originals Superstar Sneakers    16.0
Name: New Value, dtype: float64

### agg() is used to apply multiple aggregate functions

In [179]:
dffffff = df2.groupby('Product Name')['New Value'].agg(['mean','sum','count'])
dffffff

KeyError: 'Column not found: New Value'

In [180]:
type(df2)

pandas.Series

In [181]:
# Mergining and Joining DataFrames 
df1 = pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'],'Value2':[4,5,6]})

In [182]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [183]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [184]:
pd.merge(df1,df2,on='Key',how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [185]:
pd.merge(df1,df2,on = "Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [191]:
pd.merge(df1,df2,on = "Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [193]:
pd.merge(df1,df2,on = "Key",how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

# Reading Data from Different Sources

In [ ]:
from io import StringIO # Converting JSON to Df
Data = '{"employee_name":"Pranav","email":"pranavaditya45@gmail.com","job_profile":[{"title1":"Data Scientist","title2":"Data Engineer"}]}'
df = pd.read_json(StringIO(Data))
df

,employee_name,email,job_profile
0,Pranav,pranavaditya45@gmail.com,"{'title1': 'Data Scientist', 'title2': 'Data E..."

In [ ]:
df.to_json() # df to json

'{"employee_name":{"0":"Pranav"},"email":{"0":"pranavaditya45@gmail.com"},"job_profile":{"0":{"title1":"Data Scientist","title2":"Data Engineer"}}}'

In [201]:
!pip install lxml beautifulsoup4 html5lib

Collecting lxml
  Downloading lxml-6.1.1-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.5 kB)
Requirement already satisfied: beautifulsoup4 in /Users/pranavaditya/Library/Python/3.11/lib/python/site-packages (4.15.0)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/pranavaditya/Library/Python/3.11/lib/python/site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/pranavaditya/Library/Python/3.11/lib/python/site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /Users/pranavaditya/Library/Python/3.11/lib/python/site-packages (from html5lib) (0.5.1)
Downloading lxml-6.1.1-cp311-cp311-macosx_10_9_universal2.whl (8.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 12.4 MB/s eta 0:00:00a 0:00:01
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: lxml, html5lib
Successfully installed html5lib-1.1 lxml-6.1.1

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [202]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"
df = pd.read_html(url)
df

[                                            Bank Name               City  \
 0                                 Small Business Bank             Lenexa
 1       Kentland Federal Savings and Loan Association           Kentland
 2             Community Bank and Trust - West Georgia           LaGrange
 3                   Metropolitan Capital Bank & Trust            Chicago
 4                        The Santa Anna National Bank         Santa Anna
 5                                Pulaski Savings Bank            Chicago
 6                  The First National Bank of Lindsay            Lindsay
 7               Republic First Bank dba Republic Bank       Philadelphia
 8                                       Citizens Bank           Sac City
 9                            Heartland Tri-State Bank            Elkhart
 10                                First Republic Bank      San Francisco
 11                                     Signature Bank           New York
 12                                Silicon Valley Bank        Santa Clara
 13                                  Almena State Bank             Almena
 14                         First City Bank of Florida  Fort Walton Beach
 15                               The First State Bank      Barboursville
 16                                 Ericson State Bank            Ericson
 17                   City National Bank of New Jersey             Newark
 18                                      Resolute Bank             Maumee
 19                              Louisa Community Bank             Louisa
 20                               The Enloe State Bank             Cooper
 21                Washington Federal Bank for Savings            Chicago
 22    The Farmers and Merchants State Bank of Argonia            Argonia
 23                                Fayette County Bank         Saint Elmo
 24  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...          Milwaukee

             State   Cert                     Acquiring Institution  \
 0          Kansas  25744  The Farmers State Bank of Oakley, Kansas
 1         Indiana  28722                             Kentland Bank
 2         Georgia  25796                               Anchor Bank
 3        Illinois  57488                   First Independence Bank
 4           Texas   5520                 Coleman County State Bank
 5        Illinois  28611                           Millennium Bank
 6        Oklahoma   4134                    First Bank & Trust Co.
 7    Pennsylvania  27332         Fulton Bank, National Association
 8            Iowa   8758                 Iowa Trust & Savings Bank
 9          Kansas  25851                    Dream First Bank, N.A.
 10     California  59017                 JPMorgan Chase Bank, N.A.
 11       New York  57053                       Flagstar Bank, N.A.
 12     California  24735       First–Citizens Bank & Trust Company
 13         Kansas  15426                               Equity Bank
 14        Florida  16748                 United Fidelity Bank, fsb
 15  West Virginia  14361                            MVB Bank, Inc.
 16       Nebraska  18265                Farmers and Merchants Bank
 17     New Jersey  21111                           Industrial Bank
 18           Ohio  58317                        Buckeye State Bank
 19       Kentucky  58112         Kentucky Farmers Bank Corporation
 20          Texas  10716                        Legend Bank, N. A.
 21       Illinois  30570                        Royal Savings Bank
 22         Kansas  17719                               Conway Bank
 23       Illinois   1802                 United Fidelity Bank, fsb
 24      Wisconsin  30003       First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       July 17, 2026                 10553
 1       July 10, 2026                 10552
 2         May 1, 2026                 10551
 3    January 30, 2026                 10550
 4       June 27, 2025                 10549
 5    January 17, 2025                 10548
 6    October 18, 2024                 10547
 7      April 26, 2024                 10546
 8    November 3, 2023                 10545
 9       July 28, 2023                 10544
 10        May 1, 2023                 10543
 11     March 12, 2023                 10540
 12     March 10, 2023                 10539
 13   October 23, 2020                 10538
 14   October 16, 2020                 10537
 15      April 3, 2020                 10536
 16  February 14, 2020                 10535
 17   November 1, 2019                 10534
 18   October 25, 2019                 10533
 19   October 25, 2019                 10532
 20       May 31, 2019                 10531
 21  December 15, 2017                 10530
 22   October 13, 2017                 10529
 23       May 26, 2017                 10528
 24        May 5, 2017                 10527  ]

In [203]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
5,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
6,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
7,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
8,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
9,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
10,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
11,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
12,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
13,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
14,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
15,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
16,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
17,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
18,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
19,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
20,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
21,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
22,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
23,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
24,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527

In [204]:
for tab in df:
    print(tab)

                                            Bank Name               City  \
0                                 Small Business Bank             Lenexa
1       Kentland Federal Savings and Loan Association           Kentland
2             Community Bank and Trust - West Georgia           LaGrange
3                   Metropolitan Capital Bank & Trust            Chicago
4                        The Santa Anna National Bank         Santa Anna
5                                Pulaski Savings Bank            Chicago
6                  The First National Bank of Lindsay            Lindsay
7               Republic First Bank dba Republic Bank       Philadelphia
8                                       Citizens Bank           Sac City
9                            Heartland Tri-State Bank            Elkhart
10                                First Republic Bank      San Francisco
11                                     Signature Bank           New York
12                                Silicon Valley Bank        Santa Clara
13                                  Almena State Bank             Almena
14                         First City Bank of Florida  Fort Walton Beach
15                               The First State Bank      Barboursville
16                                 Ericson State Bank            Ericson
17                   City National Bank of New Jersey             Newark
18                                      Resolute Bank             Maumee
19                              Louisa Community Bank             Louisa
20                               The Enloe State Bank             Cooper
21                Washington Federal Bank for Savings            Chicago
22    The Farmers and Merchants State Bank of Argonia            Argonia
23                                Fayette County Bank         Saint Elmo
24  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...          Milwaukee

            State   Cert                     Acquiring Institution  \
0          Kansas  25744  The Farmers State Bank of Oakley, Kansas
1         Indiana  28722                             Kentland Bank
2         Georgia  25796                               Anchor Bank
3        Illinois  57488                   First Independence Bank
4           Texas   5520                 Coleman County State Bank
5        Illinois  28611                           Millennium Bank
6        Oklahoma   4134                    First Bank & Trust Co.
7    Pennsylvania  27332         Fulton Bank, National Association
8            Iowa   8758                 Iowa Trust & Savings Bank
9          Kansas  25851                    Dream First Bank, N.A.
10     California  59017                 JPMorgan Chase Bank, N.A.
11       New York  57053                       Flagstar Bank, N.A.
12     California  24735       First–Citizens Bank & Trust Company
13         Kansas  15426                               Equity Bank
14        Florida  16748                 United Fidelity Bank, fsb
15  West Virginia  14361                            MVB Bank, Inc.
16       Nebraska  18265                Farmers and Merchants Bank
17     New Jersey  21111                           Industrial Bank
18           Ohio  58317                        Buckeye State Bank
19       Kentucky  58112         Kentucky Farmers Bank Corporation
20          Texas  10716                        Legend Bank, N. A.
21       Illinois  30570                        Royal Savings Bank
22         Kansas  17719                               Conway Bank
23       Illinois   1802                 United Fidelity Bank, fsb
24      Wisconsin  30003       First-Citizens Bank & Trust Company

         Closing Date  Fund  Sort ascending
0       July 17, 2026                 10553
1       July 10, 2026                 10552
2         May 1, 2026                 10551
3    January 30, 2026                 10550
4       June 27, 2025                 10549
5    January 17, 2025                 10548
6    October 18, 2024                 10547
7      April 26, 2024                 10546
8    November 3, 2023                 10545
9       July 28, 2023                 10544
10        May 1, 2023                 10543
11     March 12, 2023                 10540
12     March 10, 2023                 10539
13   October 23, 2020                 10538
14   October 16, 2020                 10537
15      April 3, 2020                 10536
16  February 14, 2020                 10535
17   November 1, 2019                 10534
18   October 25, 2019                 10533
19   October 25, 2019                 10532
20       May 31, 2019                 10531
21  December 15, 2017                 10530
22   October 13, 2017                 10529
23       May 26, 2017                 10528
24        May 5, 2017                 10527