# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [72]:
# Create a Pandas Series with 5 random text strings
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Original Series:")
print(text_data)

# Extract the first three characters of each string
first_three_chars = text_data.str.len() # Special built in accessor object provided by pandas
print("First three characters:")
print(first_three_chars)

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: str
First three characters:
0     5
1     6
2     6
3     4
4    10
dtype: int64

In [71]:
# Create a Pandas Series with 5 random text strings
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Original Series:")
print(text_data)

# Convert all the strings to uppercase
uppercase_data = text_data.str.upper()
print("Uppercase Series:")
print(uppercase_data)

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: str
Uppercase Series:
0         APPLE
1        BANANA
2        CHERRY
3          DATE
4    ELDERBERRY
dtype: str

In [70]:
import pandas as pd 
import numpy as np 

def double(x):
    return x*2
df3 = pd.DataFrame(np.random.randint(1,100,size = (5,3)),columns = ['A','B','C'])
df3=df3.apply(double)


def summ_col(col):
    return col.sum()

df3['Total']=df3.apply(summ_col,axis=1)
df3

     A    B    C  Total
0   52   36   34    122
1   98  124   50    272
2   60  192   88    340
3  198  174   40    412
4  144  126  166    436

In [64]:
import numpy as np 
import pandas as pd
date_rng = pd.date_range(start='2022-01-01',end = '2022-01-10',freq='D')
df2 = pd.DataFrame({'Category':np.random.choice(['A','B','C'],size=20),'Date':np.random.choice(date_rng,size=20),'Value':np.random.randint(1,10,size = 20)})
df2=df2.pivot_table(values = "Value",columns = "Category",index = 'Date',aggfunc='sum')
df2



df3 = pd.DataFrame({'Year':np.random.choice([2023,2024,2025,2026],size = 20),'Quarter':np.random.choice(['Q1','Q2','Q3','Q4'],size = 20),'Revenue':np.random.randint(1,100,size = 20)})
pivot3 = df3.pivot_table(values = 'Revenue',columns = "Quarter",index = 'Year')
pivot3

Quarter    Q1    Q2    Q3    Q4
Year
2023      NaN  30.0  55.0  50.0
2024     79.0  50.5   NaN  25.5
2025     97.0   NaN  48.0  72.0
2026     95.0  21.5   NaN   NaN

In [ ]:

arrays = [['A','A','B','B'],['One','Two','One','Two']]
index = pd.MultiIndex.from_arrays(arrays,names=("Category","Sub-category"))
df1 = pd.DataFrame(np.random.randint(1,100,size = (4,3)),index = index ,columns = ['Value1','Value2','Value3'])
print(df1)

print(df1.at[('B','Two'),"Value1"])
print(df1.loc['B','Two'])
print(df1.loc['A'])

                       Value1  Value2  Value3
Category Sub-category
A        One               86      90      75
         Two               55      72      99
B        One               93      55      35
         Two               43      74      87
43
Value1    43
Value2    74
Value3    87
Name: (B, Two), dtype: int64
              Value1  Value2  Value3
Sub-category
One               86      90      75
Two               55      72      99

In [ ]:

date_rng=pd.date_range(start='2022-01-01',end = '2022-12-31',freq='D')
date_rng
data = np.random.randint(1,100,size = len(date_rng))
data
df3 = pd.DataFrame({'date':date_rng,'data':data})
df3=df3.set_index('date')
df3 = df3.resample('ME').mean()
df3.rolling(window=7).mean()

                 data
date
2022-01-31        NaN
2022-02-28        NaN
2022-03-31        NaN
2022-04-30        NaN
2022-05-31        NaN
2022-06-30        NaN
2022-07-31  50.298223
2022-08-31  49.906517
2022-09-30  50.777266
2022-10-31  49.924731
2022-11-30  50.705684
2022-12-31  50.572043

In [ ]:

df3 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})
df4 = pd.DataFrame({'E':[10,11,12],'F':[13,14,15],'G':[16,17,18]})
print("Row Axis")
print(pd.concat([df3,df4],axis = 0))
print("Column Axis")
print(pd.concat([df4,df3],axis=1))

Row Axis
     A    B    C     E     F     G
0  1.0  4.0  7.0   NaN   NaN   NaN
1  2.0  5.0  8.0   NaN   NaN   NaN
2  3.0  6.0  9.0   NaN   NaN   NaN
0  NaN  NaN  NaN  10.0  13.0  16.0
1  NaN  NaN  NaN  11.0  14.0  17.0
2  NaN  NaN  NaN  12.0  15.0  18.0
Column Axis
    E   F   G  A  B  C
0  10  13  16  1  4  7
1  11  14  17  2  5  8
2  12  15  18  3  6  9

In [13]:

df1 = pd.DataFrame({'Key':np.random.choice(['A','B','C'],size=10),'Value1':np.random.randint(1,10,size=10)})
df2 = pd.DataFrame({'Key':np.random.choice(['A','B','C'],size=10),'Value2':np.random.randint(1,10,size=10)})
print(df1)
print(df2)
df3 = pd.merge(df1,df2,how = "inner",on="Key")
df3

  Key  Value1
0   B       8
1   C       1
2   C       9
3   A       6
4   A       9
5   A       1
6   C       3
7   C       9
8   A       3
9   C       7
  Key  Value2
0   B       9
1   C       9
2   B       2
3   C       2
4   B       3
5   B       1
6   B       3
7   C       6
8   B       8
9   B       6

   Key  Value1  Value2
0    B       8       9
1    B       8       2
2    B       8       3
3    B       8       1
4    B       8       3
5    B       8       8
6    B       8       6
7    C       1       9
8    C       1       2
9    C       1       6
10   C       9       9
11   C       9       2
12   C       9       6
13   C       3       9
14   C       3       2
15   C       3       6
16   C       9       9
17   C       9       2
18   C       9       6
19   C       7       9
20   C       7       2
21   C       7       6

In [ ]:

df7 = pd.DataFrame({'Category':np.random.choice(['A','B','C'],size = 10),'value':np.random.randint(1,10,size = 10)})
df7=df7.groupby('Category')['value'].agg(['sum','mean'])
df7

          sum      mean
Category
A           6  6.000000
B          45  6.428571
C          15  7.500000

In [ ]:

df6 = pd.DataFrame(np.random.randint(1,10,size=(6,4)),columns = ['A','B','C','D'])
df6.iat[0,0]=np.nan 
df6.iat[1,2]=np.nan
df6.iat[3,2] = np.nan 
df6=df6.dropna()
df6

     A  B    C  D
2  7.0  2  4.0  5
4  6.0  1  2.0  3
5  6.0  8  5.0  2

In [ ]:
df5 = pd.DataFrame(np.random.randint(1,10,size=(5,3)),columns=['A','B','C'])
df5.iat[0,0]=np.nan 
df5.iat[1,2]=np.nan
df5.iat[3,2] = np.nan 
print(df5)
df5 = df5.fillna(df5.mean())
print(df5)

     A  B    C
0  NaN  9  3.0
1  9.0  6  NaN
2  2.0  8  5.0
3  7.0  5  NaN
4  2.0  6  7.0
     A  B    C
0  5.0  9  3.0
1  9.0  6  5.0
2  2.0  8  5.0
3  7.0  5  5.0
4  2.0  6  7.0

In [ ]:

df3 = pd.DataFrame(np.random.randint(1,10,size = (5,3)),columns=['A','B','C'])
df3['D']=df3['A']*df3['B']
df3
df4 = pd.DataFrame(np.random.randint(1,10,size=(4,3)),columns = ['A','B','C'])
df4
print(df4.sum(axis=1))
print(df4.sum(axis=0))

0    14
1    17
2    15
3    21
dtype: int64
A    23
B    18
C    26
dtype: int64

In [ ]:


df = pd.DataFrame(np.random.randint(1,10,size=(6,4)),columns=['A','B','C','D'])
df =df.set_index('A')
df

   B  C  D
A
9  6  9  6
2  2  9  8
1  3  5  9
8  5  2  1
6  5  9  8
9  5  8  9

In [ ]:
df2 = pd.DataFrame(np.random.randint(1,10,size=(3,3)),columns=['A','B','C'],index=['X','Y','Z'])
df2

   A  B  C
X  3  1  5
Y  8  1  2
Z  4  2  7

In [ ]:
df2.at['Y','B']

1

In [4]:
import numpy as np 
import pandas as pd
df8 = pd.DataFrame({'product':np.random.choice(['Iphone','Macbook','Ipad'],size=10),'Category':np.random.choice(['A','B','C'],size=10),'Sales':np.random.randint(1,10,size = 10)})
df8 = df8.groupby('Category')['Sales'].sum()
df8

Category
A     7
B    12
C    20
Name: Sales, dtype: int64