In [1]:
import pandas as pd
import re
import io

In [2]:
with open('/Users/pranavaditya/Desktop/Data-Engineering-Journey/First_Pipeline/data-ingestion/support-logs/day-wise-logs-data/support_logs_2025-07-01.log') as f:
    content = f.read()
len(content)

32938

In [ ]:
lines = content.split('---')
lines = [entry.strip() for entry in content.split('---') if entry.strip()]

'2025-07-01 14:10:00 [INFO] careplus.support.GenericService - TicketID=TCK0701029 SessionID=sess_TCK0701029\nIP=178.77.232.8 | ResponseTime=214ms | CPU=33.47% | EventType=generic_event | Error=false\nUserAgent="curl/7.68.0"\nMessage=" event for TCK0701029"\nDebug="ℹ️ Logged for monitoring"\nTraceID=None'

In [16]:
import re


fields = {
    "timestamp": r"^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})",
    "log_level": r"\[(.*?)\]",
    "service": r"\] ([\w\.]+) -",
    "ticket_id": r"TicketID=(\S+)",
    "session_id": r"SessionID=(\S+)",
    "ip": r"IP=([\d.]+)",
    "response_time": r"ResponseTime=(\d+)ms",
    "cpu": r"CPU=([\d.]+)%",
    "event_type": r"EventType=(\w+)",
    "error": r"Error=(\w+)",
    "user_agent": r'UserAgent="(.*?)"',
    "message": r'Message="(.*?)"',
    "debug": r'Debug="(.*?)"',
    "trace_id": r"TraceID=(\S+)"
}

all_logs = []

for log in lines:
    extracted = {}
    for key, pattern in fields.items():
        match = re.search(pattern, log, re.DOTALL)
        extracted[key] = match.group(1) if match else None
    all_logs.append(extracted)

print(all_logs)

[{'timestamp': '2025-07-01 00:21:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701000', 'session_id': 'sess_TCK0701000', 'ip': '60.130.155.7', 'response_time': '1269', 'cpu': '27.64', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701000', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 00:41:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701000', 'session_id': 'sess_TCK0701000', 'ip': '58.36.189.27', 'response_time': '1505', 'cpu': '57.24', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701000', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 01:44:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701001', 'session_id': 'sess_TCK0701001', 'ip': '181.18.12.170', 'response_time': '586', 'cpu': '78.43', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701001', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 01:49:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701001', 'session_id': 'sess_TCK0701001', 'ip': '163.214.94.42', 'response_time': '878', 'cpu': '63.61', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701001', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 01:50:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701000', 'session_id': 'sess_TCK0701000', 'ip': '155.68.207.12', 'response_time': '1614', 'cpu': '87.85', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701000', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 02:43:00', 'log_level': 'warnING', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701000', 'session_id': 'sess_TCK0701000', 'ip': '179.109.88.72', 'response_time': '438', 'cpu': '18.18', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701000', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 02:47:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701002', 'session_id': 'sess_TCK0701002', 'ip': '69.17.55.234', 'response_time': '1281', 'cpu': '62.44', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701002', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 03:08:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701005', 'session_id': 'sess_TCK0701005', 'ip': '18.232.9.221', 'response_time': '796', 'cpu': '32.28', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701005', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 03:27:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701005', 'session_id': 'sess_TCK0701005', 'ip': '251.195.137.197', 'response_time': '377', 'cpu': '85.75', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701005', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 03:30:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701002', 'session_id': 'sess_TCK0701002', 'ip': '36.64.191.144', 'response_time': '1223', 'cpu': '81.83', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701002', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 03:30:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701002', 'session_id': 'sess_TCK0701002', 'ip': '36.64.191.144', 'response_time': '1223', 'cpu': '81.83', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701002', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 03:49:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701005', 'session_id': 'sess_TCK0701005', 'ip': '238.139.194.187', 'response_time': '1532', 'cpu': '41.92', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701005', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:01:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701003', 'session_id': 'sess_TCK0701003', 'ip': '24.194.13.221', 'response_time': '344', 'cpu': '73.37', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701003', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:14:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701006', 'session_id': 'sess_TCK0701006', 'ip': '201.122.207.105', 'response_time': '509', 'cpu': '62.72', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701006', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:17:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701003', 'session_id': 'sess_TCK0701003', 'ip': '153.120.136.65', 'response_time': '1253', 'cpu': '64.54', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701003', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:23:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701001', 'session_id': 'sess_TCK0701001', 'ip': '42.119.98.70', 'response_time': '1430', 'cpu': '64.77', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701001', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:30:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701007', 'session_id': 'sess_TCK0701007', 'ip': '15.246.131.21', 'response_time': '500', 'cpu': '64.02', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701007', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:46:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701003', 'session_id': 'sess_TCK0701003', 'ip': '76.112.41.117', 'response_time': '126', 'cpu': '50.61', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701003', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:46:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701006', 'session_id': 'sess_TCK0701006', 'ip': '49.138.115.36', 'response_time': '984', 'cpu': '47.01', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701006', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 04:50:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701006', 'session_id': 'sess_TCK0701006', 'ip': '222.187.14.173', 'response_time': '1458', 'cpu': '42.21', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701006', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:08:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701004', 'session_id': 'sess_TCK0701004', 'ip': '225.253.213.207', 'response_time': None, 'cpu': '29.27', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701004', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:08:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701007', 'session_id': 'sess_TCK0701007', 'ip': '102.34.172.166', 'response_time': '734', 'cpu': '84.32', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701007', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:10:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701007', 'session_id': 'sess_TCK0701007', 'ip': '98.1.253.100', 'response_time': '663', 'cpu': '43.84', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701007', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:11:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701008', 'session_id': 'sess_TCK0701008', 'ip': '138.55.130.68', 'response_time': '391', 'cpu': '80.34', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701008', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:16:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701007', 'session_id': 'sess_TCK0701007', 'ip': '149.153.11.159', 'response_time': None, 'cpu': '84.78', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701007', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:21:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701009', 'session_id': 'sess_TCK0701009', 'ip': '164.251.68.42', 'response_time': '1638', 'cpu': '54.87', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701009', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:38:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701009', 'session_id': 'sess_TCK0701009', 'ip': '214.95.150.142', 'response_time': '423', 'cpu': '13.35', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701009', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:43:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701004', 'session_id': 'sess_TCK0701004', 'ip': '96.196.42.139', 'response_time': '1714', 'cpu': '57.92', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701004', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:45:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701010', 'session_id': 'sess_TCK0701010', 'ip': '171.27.91.200', 'response_time': '1266', 'cpu': '84.06', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701010', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 05:58:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701005', 'session_id': 'sess_TCK0701005', 'ip': '31.64.58.17', 'response_time': '812', 'cpu': '57.08', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701005', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:03:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701009', 'session_id': 'sess_TCK0701009', 'ip': '130.126.65.232', 'response_time': None, 'cpu': '76.35', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701009', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:09:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701007', 'session_id': 'sess_TCK0701007', 'ip': '249.24.238.193', 'response_time': '604', 'cpu': '48.85', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701007', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:26:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701009', 'session_id': 'sess_TCK0701009', 'ip': '30.228.28.191', 'response_time': '1253', 'cpu': '32.54', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701009', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:26:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701009', 'session_id': 'sess_TCK0701009', 'ip': '30.228.28.191', 'response_time': '1253', 'cpu': '32.54', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701009', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:32:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701012', 'session_id': 'sess_TCK0701012', 'ip': '84.104.179.76', 'response_time': '1255', 'cpu': '43.64', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701012', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:35:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701010', 'session_id': 'sess_TCK0701010', 'ip': '7.46.189.237', 'response_time': '800', 'cpu': '31.34', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701010', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:38:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701007', 'session_id': 'sess_TCK0701007', 'ip': '76.56.248.15', 'response_time': '1306', 'cpu': '69.84', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701007', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:43:00', 'log_level': 'DEBG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701008', 'session_id': 'sess_TCK0701008', 'ip': '214.140.181.78', 'response_time': '1372', 'cpu': '63.43', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701008', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:43:00', 'log_level': 'DEBG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701008', 'session_id': 'sess_TCK0701008', 'ip': '214.140.181.78', 'response_time': '1372', 'cpu': '63.43', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701008', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 06:53:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701011', 'session_id': 'sess_TCK0701011', 'ip': '85.72.222.18', 'response_time': '1703', 'cpu': '61.32', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701011', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 07:29:00', 'log_level': 'DEBUG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701012', 'session_id': 'sess_TCK0701012', 'ip': '99.231.148.49', 'response_time': None, 'cpu': '10.14', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701012', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 07:38:00', 'log_level': 'DEBG', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701011', 'session_id': 'sess_TCK0701011', 'ip': '225.249.67.46', 'response_time': '1309', 'cpu': '18.67', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'curl/7.68.0', 'message': ' event for TCK0701011', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 07:53:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701014', 'session_id': 'sess_TCK0701014', 'ip': '57.46.206.246', 'response_time': '1545', 'cpu': '14.02', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701014', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 07:57:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701018', 'session_id': 'sess_TCK0701018', 'ip': '167.18.200.246', 'response_time': '1454', 'cpu': '85.97', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701018', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 07:57:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701018', 'session_id': 'sess_TCK0701018', 'ip': '167.18.200.246', 'response_time': '1454', 'cpu': '85.97', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0)', 'message': ' event for TCK0701018', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 08:18:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701012', 'session_id': 'sess_TCK0701012', 'ip': '18.243.171.236', 'response_time': '796', 'cpu': '63.07', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701012', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 08:19:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701014', 'session_id': 'sess_TCK0701014', 'ip': '206.119.171.136', 'response_time': '1264', 'cpu': '86.0', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Mobile-Safari/537.36', 'message': ' event for TCK0701014', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 08:34:00', 'log_level': 'INF0', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701010', 'session_id': 'sess_TCK0701010', 'ip': '220.121.57.52', 'response_time': '1792', 'cpu': '34.42', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'Python-urllib/3.9', 'message': ' event for TCK0701010', 'debug': 'ℹ️ Logged for monitoring', 'trace_id': 'None'}, {'timestamp': '2025-07-01 08:44:00', 'log_level': 'INFO', 'service': 'careplus.support.GenericService', 'ticket_id': 'TCK0701018', 'session_id': 'sess_TCK0701018', 'ip': '33.122.172.30', 'response_time': '1275', 'cpu': '65.96', 'event_type': 'generic_event', 'error': 'false', 'user_agent': 'PostmanRuntime/7.32.2', 'message': ' event for TCK0701018', 'debug': 'ℹ️ Logg

In [18]:
df = pd.DataFrame(all_logs)
df.head()

,timestamp,log_level,service,ticket_id,session_id,ip,response_time,cpu,event_type,error,user_agent,message,debug,trace_id
0,2025-07-01 00:21:00,INF0,careplus.support.GenericService,TCK0701000,sess_TCK0701000,60.130.155.7,1269,27.64,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701000,ℹ️ Logged for monitoring,None
1,2025-07-01 00:41:00,INFO,careplus.support.GenericService,TCK0701000,sess_TCK0701000,58.36.189.27,1505,57.24,generic_event,false,Mobile-Safari/537.36,event for TCK0701000,ℹ️ Logged for monitoring,None
2,2025-07-01 01:44:00,DEBUG,careplus.support.GenericService,TCK0701001,sess_TCK0701001,181.18.12.170,586,78.43,generic_event,false,curl/7.68.0,event for TCK0701001,ℹ️ Logged for monitoring,None
3,2025-07-01 01:49:00,DEBUG,careplus.support.GenericService,TCK0701001,sess_TCK0701001,163.214.94.42,878,63.61,generic_event,false,curl/7.68.0,event for TCK0701001,ℹ️ Logged for monitoring,None
4,2025-07-01 01:50:00,INFO,careplus.support.GenericService,TCK0701000,sess_TCK0701000,155.68.207.12,1614,87.85,generic_event,false,Python-urllib/3.9,event for TCK0701000,ℹ️ Logged for monitoring,None

In [19]:
df.describe()

,timestamp,log_level,service,ticket_id,session_id,ip,response_time,cpu,event_type,error,user_agent,message,debug,trace_id
count,105,105,105,105,105,105,98,105,105,105,105,105,105,105
unique,90,6,1,30,30,96,85,96,1,1,5,30,1,1
top,2025-07-01 03:30:00,INFO,careplus.support.GenericService,TCK0701028,sess_TCK0701028,36.64.191.144,1253,81.83,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701028,ℹ️ Logged for monitoring,None
freq,2,40,105,7,7,2,3,2,105,105,27,7,105,105

In [22]:
df = df.drop('trace_id',axis=1)

In [23]:
df

,timestamp,log_level,service,ticket_id,session_id,ip,response_time,cpu,event_type,error,user_agent,message,debug
0,2025-07-01 00:21:00,INF0,careplus.support.GenericService,TCK0701000,sess_TCK0701000,60.130.155.7,1269,27.64,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701000,ℹ️ Logged for monitoring
1,2025-07-01 00:41:00,INFO,careplus.support.GenericService,TCK0701000,sess_TCK0701000,58.36.189.27,1505,57.24,generic_event,false,Mobile-Safari/537.36,event for TCK0701000,ℹ️ Logged for monitoring
2,2025-07-01 01:44:00,DEBUG,careplus.support.GenericService,TCK0701001,sess_TCK0701001,181.18.12.170,586,78.43,generic_event,false,curl/7.68.0,event for TCK0701001,ℹ️ Logged for monitoring
3,2025-07-01 01:49:00,DEBUG,careplus.support.GenericService,TCK0701001,sess_TCK0701001,163.214.94.42,878,63.61,generic_event,false,curl/7.68.0,event for TCK0701001,ℹ️ Logged for monitoring
4,2025-07-01 01:50:00,INFO,careplus.support.GenericService,TCK0701000,sess_TCK0701000,155.68.207.12,1614,87.85,generic_event,false,Python-urllib/3.9,event for TCK0701000,ℹ️ Logged for monitoring
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2025-07-01 13:01:00,INFO,careplus.support.GenericService,TCK0701027,sess_TCK0701027,198.203.219.107,816,75.64,generic_event,false,Mobile-Safari/537.36,event for TCK0701027,ℹ️ Logged for monitoring
101,2025-07-01 13:03:00,INFO,careplus.support.GenericService,TCK0701025,sess_TCK0701025,140.58.166.39,664,14.77,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701025,ℹ️ Logged for monitoring
102,2025-07-01 13:13:00,INF0,careplus.support.GenericService,TCK0701028,sess_TCK0701028,162.176.236.74,585,88.27,generic_event,false,Mozilla/5.0 (Windows NT 10.0),event for TCK0701028,ℹ️ Logged for monitoring
103,2025-07-01 13:46:00,DEBG,careplus.support.GenericService,TCK0701029,sess_TCK0701029,234.150.37.60,1064,30.43,generic_event,false,curl/7.68.0,event for TCK0701029,ℹ️ Logged for monitoring
104,2025-07-01 14:10:00,INFO,careplus.support.GenericService,TCK0701029,sess_TCK0701029,178.77.232.8,214,33.47,generic_event,false,curl/7.68.0,event for TCK0701029,ℹ️ Logged for monitoring

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      105 non-null    str
 1   log_level      105 non-null    str
 2   service        105 non-null    str
 3   ticket_id      105 non-null    str
 4   session_id     105 non-null    str
 5   ip             105 non-null    str
 6   response_time  98 non-null     str
 7   cpu            105 non-null    str
 8   event_type     105 non-null    str
 9   error          105 non-null    str
 10  user_agent     105 non-null    str
 11  message        105 non-null    str
 12  debug          105 non-null    str
dtypes: str(13)
memory usage: 30.0 KB

In [25]:
df = df.astype({"cpu": "float"})
df["response_time"] = pd.to_numeric(df["response_time"], errors="coerce").astype("Int64")
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      105 non-null    datetime64[us]
 1   log_level      105 non-null    str
 2   service        105 non-null    str
 3   ticket_id      105 non-null    str
 4   session_id     105 non-null    str
 5   ip             105 non-null    str
 6   response_time  98 non-null     Int64
 7   cpu            105 non-null    float64
 8   event_type     105 non-null    str
 9   error          105 non-null    str
 10  user_agent     105 non-null    str
 11  message        105 non-null    str
 12  debug          105 non-null    str
dtypes: Int64(1), datetime64[us](1), float64(1), str(10)
memory usage: 27.3 KB

In [27]:
df.describe()

                        timestamp  response_time         cpu
count                         105           98.0  105.000000
mean   2025-07-01 08:21:31.428571         1006.5   54.918190
min           2025-07-01 00:21:00          126.0   10.140000
25%           2025-07-01 05:38:00         653.25   34.420000
50%           2025-07-01 09:13:00         1089.0   60.140000
75%           2025-07-01 11:12:00        1327.75   73.700000
max           2025-07-01 14:10:00         1792.0   89.970000
std                           NaN     447.808944   22.513155

In [28]:
df['log_level'].value_counts()

log_level
INFO       40
DEBUG      36
INF0       13
DEBG       10
warnING     3
WARNING     3
Name: count, dtype: int64

In [29]:
fixes = {'INF0':'INFO','warnING':'WARNING','DEBG':'DEBUG'}
df['log_level'] = df['log_level'].replace(fixes)
df.log_level.value_counts()

log_level
INFO       53
DEBUG      46
WARNING     6
Name: count, dtype: int64

In [30]:
df[df.duplicated()]

,timestamp,log_level,service,ticket_id,session_id,ip,response_time,cpu,event_type,error,user_agent,message,debug
10,2025-07-01 03:30:00,DEBUG,careplus.support.GenericService,TCK0701002,sess_TCK0701002,36.64.191.144,1223,81.83,generic_event,false,curl/7.68.0,event for TCK0701002,ℹ️ Logged for monitoring
33,2025-07-01 06:26:00,INFO,careplus.support.GenericService,TCK0701009,sess_TCK0701009,30.228.28.191,1253,32.54,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701009,ℹ️ Logged for monitoring
38,2025-07-01 06:43:00,DEBUG,careplus.support.GenericService,TCK0701008,sess_TCK0701008,214.140.181.78,1372,63.43,generic_event,false,Mobile-Safari/537.36,event for TCK0701008,ℹ️ Logged for monitoring
44,2025-07-01 07:57:00,INFO,careplus.support.GenericService,TCK0701018,sess_TCK0701018,167.18.200.246,1454,85.97,generic_event,false,Mozilla/5.0 (Windows NT 10.0),event for TCK0701018,ℹ️ Logged for monitoring
57,2025-07-01 09:32:00,DEBUG,careplus.support.GenericService,TCK0701013,sess_TCK0701013,114.173.55.131,1089,32.70,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701013,ℹ️ Logged for monitoring
59,2025-07-01 09:36:00,DEBUG,careplus.support.GenericService,TCK0701020,sess_TCK0701020,146.157.172.98,808,78.08,generic_event,false,Mozilla/5.0 (Windows NT 10.0),event for TCK0701020,ℹ️ Logged for monitoring
69,2025-07-01 10:17:00,INFO,careplus.support.GenericService,TCK0701019,sess_TCK0701019,163.229.213.118,1568,24.09,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701019,ℹ️ Logged for monitoring
77,2025-07-01 10:45:00,INFO,careplus.support.GenericService,TCK0701023,sess_TCK0701023,30.211.17.103,1127,22.14,generic_event,false,Mozilla/5.0 (Windows NT 10.0),event for TCK0701023,ℹ️ Logged for monitoring
92,2025-07-01 12:25:00,DEBUG,careplus.support.GenericService,TCK0701028,sess_TCK0701028,138.124.89.86,1250,46.43,generic_event,false,Mobile-Safari/537.36,event for TCK0701028,ℹ️ Logged for monitoring

In [38]:
df[df.duplicated()]

,timestamp,log_level,service,ticket_id,session_id,ip,response_time,cpu,event_type,error,user_agent,message,debug
10,2025-07-01 03:30:00,DEBUG,careplus.support.GenericService,TCK0701002,sess_TCK0701002,36.64.191.144,1223,81.83,generic_event,false,curl/7.68.0,event for TCK0701002,ℹ️ Logged for monitoring
33,2025-07-01 06:26:00,INFO,careplus.support.GenericService,TCK0701009,sess_TCK0701009,30.228.28.191,1253,32.54,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701009,ℹ️ Logged for monitoring
38,2025-07-01 06:43:00,DEBUG,careplus.support.GenericService,TCK0701008,sess_TCK0701008,214.140.181.78,1372,63.43,generic_event,false,Mobile-Safari/537.36,event for TCK0701008,ℹ️ Logged for monitoring
44,2025-07-01 07:57:00,INFO,careplus.support.GenericService,TCK0701018,sess_TCK0701018,167.18.200.246,1454,85.97,generic_event,false,Mozilla/5.0 (Windows NT 10.0),event for TCK0701018,ℹ️ Logged for monitoring
57,2025-07-01 09:32:00,DEBUG,careplus.support.GenericService,TCK0701013,sess_TCK0701013,114.173.55.131,1089,32.70,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701013,ℹ️ Logged for monitoring
59,2025-07-01 09:36:00,DEBUG,careplus.support.GenericService,TCK0701020,sess_TCK0701020,146.157.172.98,808,78.08,generic_event,false,Mozilla/5.0 (Windows NT 10.0),event for TCK0701020,ℹ️ Logged for monitoring
69,2025-07-01 10:17:00,INFO,careplus.support.GenericService,TCK0701019,sess_TCK0701019,163.229.213.118,1568,24.09,generic_event,false,PostmanRuntime/7.32.2,event for TCK0701019,ℹ️ Logged for monitoring
77,2025-07-01 10:45:00,INFO,careplus.support.GenericService,TCK0701023,sess_TCK0701023,30.211.17.103,1127,22.14,generic_event,false,Mozilla/5.0 (Windows NT 10.0),event for TCK0701023,ℹ️ Logged for monitoring
92,2025-07-01 12:25:00,DEBUG,careplus.support.GenericService,TCK0701028,sess_TCK0701028,138.124.89.86,1250,46.43,generic_event,false,Mobile-Safari/537.36,event for TCK0701028,ℹ️ Logged for monitoring

In [39]:
df = df.drop_duplicates()
df[df.duplicated()]

Empty DataFrame
Columns: [timestamp, log_level, service, ticket_id, session_id, ip, response_time, cpu, event_type, error, user_agent, message, debug]
Index: []

In [40]:
df.shape

(96, 13)